### PR TITLE
🐛️(frontend) fix SimpleLayout

### LINKED ISSUE #213: Extra padding on illustration section
## Bug Report

**Problematic behavior**
On desktop, the page is vertically divided in two section. An illustration section then the content section.

Currently the illustration section has a padding of 2rem all around so the illustration used does not stick on edges that look visually weird.

**Expected behavior/code**
The illustration section should not have padding in order to stick illustration on left and bottom edges.

**Possible Solution**
1. Remove the `padding: 2rem` to the illustration box component.
2. Display the illustration through CSS with `background-image` and keep only the FUN Logo as image. From my point of view, this solution is more semantically adapted.

**Additional context/Screenshots**
image

### PR DESCRIPTION
**Pull request by PanchoutNathan**
## Purpose

Currently the illustration section has a padding of 2rem all around so the illustration used does not stick on edges that look visually weird.

## Proposal

- Remove the padding: 2rem to the illustration box component.
- Display the illustration through CSS with background-image and keep only the FUN Logo as image.

Close #213

### CODE REVIEW

File: src/frontend/packages/core/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx [hunk 1]
```diff
@@ -1,7 +1,112 @@
...
+//           )}
+//
+//           {isLog && <ResponsiveLayoutHeaderAvatar />}
+//         </Box>
+//         {props.children}
+//       </Box>
+//     </Box>
+//   );
+// };
+
```
Comment (jbpenrath) [inline src/frontend/packages/core/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx:105]: What is this ?

File: src/frontend/packages/core/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx [hunk 2]
```diff
@@ -40,67 +145,65 @@ export const SimpleLayout = ({ urlLogo, ...props }: PropsWithChildren<Props>) =>
...
+                    {intl.formatMessage(messages.register)}
+                  </Button>
+                )}
 
-              <Button color="primary" onClick={() => router.goToLogin()} size={'small'}>
-                {intl.formatMessage(messages.login)}
-              </Button>
-            </Fragment>
-          )}
+                <Button color="primary" onClick={() => router.goToLogin()} size={'small'}>
```
Comment (jbpenrath) [inline src/frontend/packages/core/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx:196]:
```suggestion
                <Button color="primary" onClick={router.goToLogin} size={'small'}>
```

File: src/frontend/packages/core/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx [hunk 3]
```diff
@@ -40,67 +40,65 @@ export const SimpleLayout = ({ urlLogo, ...props }: PropsWithChildren<Props>) =>
...
-                <Button color="secondary" onClick={() => router.goToRegister()} size={'small'}>
-                  {intl.formatMessage(messages.register)}
-                </Button>
-              )}
+        <div>
+          <Box direction={'row'} style={{ gap: '20px', position: 'absolute', top: 20, right: 20 }}>
+            {!isLog && (
+              <>
+                {window.config.MAGNIFY_SHOW_REGISTER_LINK && (
+                  <Button color="secondary" onClick={() => router.goToRegister()} size={'small'}>
```
Comment (jbpenrath) [inline src/frontend/packages/core/src/components/design-system/Layout/SimpleLayout/SimpleLayout.tsx:86]:
```suggestion
                  <Button color="secondary" onClick={router.goToRegister} size={'small'}>
```

**Review by jbpenrath — APPROVED** [review]
LGTM ✅
